import { WatchFaceConfig } from '../types/watchface';

export const DIAL_TEXTURES = {
  carbon_fiber: '/src/assets/images/texture_carbon_fiber_1791115966485.jpg',
  brushed_titanium: '/src/assets/images/texture_brushed_titanium_1791115979741.jpg',
  cosmic_nebula: '/src/assets/images/texture_cosmic_nebula_1791115990300.jpg',
};

export const PRESET_WATCH_FACES: WatchFaceConfig[] = [
  {
    id: 'preset-apex-chrono',
    name: 'Apex Chrono 300M',
    category: 'Luxury',
    description: 'Swiss-inspired luxury titanium chronograph with tachymeter bezel and tri-subdial complication layout.',
    shape: 'round',
    caseFinish: 'titanium',
    strap: 'titanium_link',
    bezel: {
      style: 'tachymeter',
      bezelColor: '#1c1f24',
      textColor: '#e2e8f0',
      accentColor: '#d97706',
      showGlassGlare: true,
      glareIntensity: 0.28,
    },
    dial: {
      backgroundType: 'brushed_titanium',
      primaryColor: '#181a1f',
      secondaryColor: '#0f1115',
      accentColor: '#f59e0b',
      vignette: 0.45,
      innerRingRadius: 82,
      innerRingColor: '#2b303c',
      showInnerRing: true,
    },
    index: {
      style: 'classic_baton',
      color: '#f8fafc',
      glowColor: '#38bdf8',
      showSubMinutes: true,
      subMinuteColor: '#64748b',
      numberScale: 1.0,
      showCardinalsOnly: false,
    },
    timeDisplay: {
      type: 'analog',
      analog: {
        handStyle: 'dauphine',
        hourHandColor: '#f1f5f9',
        minuteHandColor: '#e2e8f0',
        secondHandColor: '#ef4444',
        lumeColor: '#38bdf8',
        sweepSeconds: true,
        showSeconds: true,
        centerCapColor: '#d97706',
        centerCapSize: 10,
      },
      digital: {
        fontFamily: 'jetbrains',
        format: '24h',
        showSeconds: false,
        showAmPm: false,
        blinkColon: true,
        textColor: '#e2e8f0',
        glowColor: '#38bdf8',
        x: 0,
        y: 20,
        fontSize: 16,
        letterSpacing: 2,
      },
    },
    brandText: {
      show: true,
      text: 'MOROKIT CRAFT',
      subtext: 'OFFICIALLY CERTIFIED',
      color: '#cbd5e1',
      y: -22,
    },
    complications: [
      {
        id: 'comp-1',
        type: 'date_window',
        style: 'compact_badge',
        x: 28,
        y: 0,
        scale: 1.05,
        color: '#f8fafc',
        accentColor: '#38bdf8',
        showIcon: false,
        showLabel: false,
      },
      {
        id: 'comp-2',
        type: 'battery',
        style: 'subdial_analog',
        x: -22,
        y: 0,
        scale: 0.95,
        color: '#f8fafc',
        accentColor: '#f59e0b',
        showIcon: true,
        showLabel: true,
        label: 'PWR',
      },
      {
        id: 'comp-3',
        type: 'heart_rate',
        style: 'ring_gauge',
        x: 0,
        y: 24,
        scale: 0.95,
        color: '#f43f5e',
        accentColor: '#fb7185',
        showIcon: true,
        showLabel: true,
        label: 'BPM',
      },
    ],
    aod: {
      enabled: true,
      dimLevel: 0.35,
      hideSeconds: true,
      outlineHands: true,
      hideComplicationGauges: true,
    },
  },
  {
    id: 'preset-cyberpunk-hud',
    name: 'Cyberpunk HUD 2077',
    category: 'Digital',
    description: 'High-tech telemetry digital face with neon phosphor HUD readouts, battery arc, and carbon fiber dial.',
    shape: 'square',
    caseFinish: 'obsidian',
    strap: 'silicone_orange',
    bezel: {
      style: 'clean',
      bezelColor: '#0a0d12',
      textColor: '#06b6d4',
      accentColor: '#f59e0b',
      showGlassGlare: true,
      glareIntensity: 0.15,
    },
    dial: {
      backgroundType: 'carbon_fiber',
      primaryColor: '#080a0f',
      secondaryColor: '#0f172a',
      accentColor: '#06b6d4',
      vignette: 0.6,
      innerRingRadius: 88,
      innerRingColor: '#1e293b',
      showInnerRing: true,
    },
    index: {
      style: 'military_24h',
      color: '#334155',
      glowColor: '#06b6d4',
      showSubMinutes: false,
      subMinuteColor: '#1e293b',
      numberScale: 0.9,
      showCardinalsOnly: true,
    },
    timeDisplay: {
      type: 'digital',
      analog: {
        handStyle: 'baton',
        hourHandColor: '#06b6d4',
        minuteHandColor: '#38bdf8',
        secondHandColor: '#f59e0b',
        lumeColor: '#06b6d4',
        sweepSeconds: false,
        showSeconds: true,
        centerCapColor: '#f59e0b',
        centerCapSize: 8,
      },
      digital: {
        fontFamily: 'orbitron',
        format: '24h',
        showSeconds: true,
        showAmPm: false,
        blinkColon: true,
        textColor: '#06b6d4',
        glowColor: '#22d3ee',
        x: 0,
        y: -6,
        fontSize: 38,
        letterSpacing: 3,
      },
    },
    brandText: {
      show: true,
      text: 'CYBER·X',
      subtext: 'SYSTEM NOMINAL',
      color: '#64748b',
      y: -30,
    },
    complications: [
      {
        id: 'comp-cp-1',
        type: 'battery',
        style: 'ring_gauge',
        x: -24,
        y: 22,
        scale: 0.95,
        color: '#06b6d4',
        accentColor: '#22d3ee',
        showIcon: true,
        showLabel: true,
        label: 'BAT',
      },
      {
        id: 'comp-cp-2',
        type: 'heart_rate',
        style: 'ring_gauge',
        x: 24,
        y: 22,
        scale: 0.95,
        color: '#f43f5e',
        accentColor: '#fb7185',
        showIcon: true,
        showLabel: true,
        label: 'PULSE',
      },
      {
        id: 'comp-cp-3',
        type: 'steps',
        style: 'compact_badge',
        x: 0,
        y: 26,
        scale: 0.9,
        color: '#f59e0b',
        accentColor: '#fbbf24',
        showIcon: true,
        showLabel: true,
        label: 'STEPS',
      },
    ],
    aod: {
      enabled: true,
      dimLevel: 0.25,
      hideSeconds: true,
      outlineHands: false,
      hideComplicationGauges: true,
    },
  },
  {
    id: 'preset-aerofit-pulse',
    name: 'AeroFit Tri-Ring',
    category: 'Sport',
    description: 'Vibrant fitness activity tracker with multi-color concentric goal rings and high-visibility digital clock.',
    shape: 'round',
    caseFinish: 'stainless',
    strap: 'silicone_black',
    bezel: {
      style: 'minimal_dots',
      bezelColor: '#111827',
      textColor: '#9ca3af',
      accentColor: '#10b981',
      showGlassGlare: true,
      glareIntensity: 0.2,
    },
    dial: {
      backgroundType: 'solid',
      primaryColor: '#090d16',
      secondaryColor: '#020617',
      accentColor: '#10b981',
      vignette: 0.5,
      innerRingRadius: 75,
      innerRingColor: '#1e293b',
      showInnerRing: false,
    },
    index: {
      style: 'minimal_ticks',
      color: '#374151',
      glowColor: '#10b981',
      showSubMinutes: false,
      subMinuteColor: '#1f2937',
      numberScale: 1.0,
      showCardinalsOnly: false,
    },
    timeDisplay: {
      type: 'hybrid',
      analog: {
        handStyle: 'minimal_needle',
        hourHandColor: '#f3f4f6',
        minuteHandColor: '#e5e7eb',
        secondHandColor: '#10b981',
        lumeColor: '#10b981',
        sweepSeconds: true,
        showSeconds: true,
        centerCapColor: '#10b981',
        centerCapSize: 7,
      },
      digital: {
        fontFamily: 'bebas',
        format: '12h',
        showSeconds: false,
        showAmPm: true,
        blinkColon: false,
        textColor: '#f9fafb',
        glowColor: '#10b981',
        x: 0,
        y: -18,
        fontSize: 32,
        letterSpacing: 2,
      },
    },
    brandText: {
      show: false,
      text: 'AEROFIT',
      subtext: 'PRO EDITION',
      color: '#6b7280',
      y: -25,
    },
    complications: [
      {
        id: 'comp-fit-1',
        type: 'steps',
        style: 'ring_gauge',
        x: -22,
        y: 16,
        scale: 1.05,
        color: '#10b981',
        accentColor: '#34d399',
        showIcon: true,
        showLabel: true,
        label: 'STEPS',
      },
      {
        id: 'comp-fit-2',
        type: 'calories',
        style: 'ring_gauge',
        x: 22,
        y: 16,
        scale: 1.05,
        color: '#f97316',
        accentColor: '#fb923c',
        showIcon: true,
        showLabel: true,
        label: 'KCAL',
      },
      {
        id: 'comp-fit-3',
        type: 'heart_rate',
        style: 'compact_badge',
        x: 0,
        y: 28,
        scale: 0.95,
        color: '#ef4444',
        accentColor: '#f87171',
        showIcon: true,
        showLabel: true,
        label: 'HR',
      },
    ],
    aod: {
      enabled: true,
      dimLevel: 0.3,
      hideSeconds: true,
      outlineHands: true,
      hideComplicationGauges: true,
    },
  },
  {
    id: 'preset-bauhaus-minimal',
    name: 'Bauhaus Werkstatt',
    category: 'Minimal',
    description: 'Modernist German typography with pure geometric harmony, primary color accents, and needle hands.',
    shape: 'round',
    caseFinish: 'rosegold',
    strap: 'leather_brown',
    bezel: {
      style: 'clean',
      bezelColor: '#18181b',
      textColor: '#a1a1aa',
      accentColor: '#ef4444',
      showGlassGlare: true,
      glareIntensity: 0.35,
    },
    dial: {
      backgroundType: 'solid',
      primaryColor: '#fafaf9',
      secondaryColor: '#f5f5f4',
      accentColor: '#ef4444',
      vignette: 0.15,
      innerRingRadius: 80,
      innerRingColor: '#e7e5e4',
      showInnerRing: true,
    },
    index: {
      style: 'arabic_sport',
      color: '#1c1917',
      glowColor: '#ef4444',
      showSubMinutes: true,
      subMinuteColor: '#a8a29e',
      numberScale: 1.1,
      showCardinalsOnly: false,
    },
    timeDisplay: {
      type: 'analog',
      analog: {
        handStyle: 'minimal_needle',
        hourHandColor: '#1c1917',
        minuteHandColor: '#1c1917',
        secondHandColor: '#ef4444',
        lumeColor: '#ef4444',
        sweepSeconds: true,
        showSeconds: true,
        centerCapColor: '#ef4444',
        centerCapSize: 8,
      },
      digital: {
        fontFamily: 'syne',
        format: '24h',
        showSeconds: false,
        showAmPm: false,
        blinkColon: true,
        textColor: '#1c1917',
        glowColor: '#ef4444',
        x: 0,
        y: 20,
        fontSize: 16,
        letterSpacing: 2,
      },
    },
    brandText: {
      show: true,
      text: 'WERKSTATT',
      subtext: 'AUTOMATIK',
      color: '#57534e',
      y: -22,
    },
    complications: [
      {
        id: 'comp-bau-1',
        type: 'date_window',
        style: 'compact_badge',
        x: 0,
        y: 18,
        scale: 1.0,
        color: '#1c1917',
        accentColor: '#ef4444',
        showIcon: false,
        showLabel: false,
      },
      {
        id: 'comp-bau-2',
        type: 'battery',
        style: 'minimal_text',
        x: -24,
        y: 0,
        scale: 0.9,
        color: '#1c1917',
        accentColor: '#3b82f6',
        showIcon: true,
        showLabel: true,
        label: 'BAT',
      },
    ],
    aod: {
      enabled: true,
      dimLevel: 0.4,
      hideSeconds: true,
      outlineHands: true,
      hideComplicationGauges: true,
    },
  },
  {
    id: 'preset-cosmos-lunar',
    name: 'Cosmos Lunar Eclipse',
    category: 'Luxury',
    description: 'Astronomical celestial timepiece with realistic moon phase dial, starfield backdrop, and golden indices.',
    shape: 'round',
    caseFinish: 'rosegold',
    strap: 'leather_brown',
    bezel: {
      style: 'numbered_12',
      bezelColor: '#12131c',
      textColor: '#fbbf24',
      accentColor: '#f59e0b',
      showGlassGlare: true,
      glareIntensity: 0.3,
    },
    dial: {
      backgroundType: 'cosmic_nebula',
      primaryColor: '#0a0b16',
      secondaryColor: '#13122c',
      accentColor: '#fbbf24',
      vignette: 0.4,
      innerRingRadius: 78,
      innerRingColor: '#2d284f',
      showInnerRing: true,
    },
    index: {
      style: 'roman_luxury',
      color: '#fbbf24',
      glowColor: '#fde68a',
      showSubMinutes: true,
      subMinuteColor: '#938fa7',
      numberScale: 1.05,
      showCardinalsOnly: false,
    },
    timeDisplay: {
      type: 'analog',
      analog: {
        handStyle: 'skeleton',
        hourHandColor: '#fbbf24',
        minuteHandColor: '#fde68a',
        secondHandColor: '#60a5fa',
        lumeColor: '#fde68a',
        sweepSeconds: true,
        showSeconds: true,
        centerCapColor: '#fbbf24',
        centerCapSize: 10,
      },
      digital: {
        fontFamily: 'cinzel',
        format: '24h',
        showSeconds: false,
        showAmPm: false,
        blinkColon: false,
        textColor: '#fbbf24',
        glowColor: '#fde68a',
        x: 0,
        y: 20,
        fontSize: 16,
        letterSpacing: 2,
      },
    },
    brandText: {
      show: true,
      text: 'ASTRONOMIA',
      subtext: 'LUNAR REPEATER',
      color: '#d4af37',
      y: -24,
    },
    complications: [
      {
        id: 'comp-cos-1',
        type: 'moon_phase',
        style: 'subdial_analog',
        x: 0,
        y: 18,
        scale: 1.25,
        color: '#fbbf24',
        accentColor: '#60a5fa',
        showIcon: false,
        showLabel: false,
        label: 'MOON',
      },
      {
        id: 'comp-cos-2',
        type: 'battery',
        style: 'ring_gauge',
        x: -24,
        y: -4,
        scale: 0.9,
        color: '#fbbf24',
        accentColor: '#f59e0b',
        showIcon: true,
        showLabel: true,
        label: 'PWR',
      },
      {
        id: 'comp-cos-3',
        type: 'weather',
        style: 'compact_badge',
        x: 24,
        y: -4,
        scale: 0.9,
        color: '#60a5fa',
        accentColor: '#93c5fd',
        showIcon: true,
        showLabel: false,
      },
    ],
    aod: {
      enabled: true,
      dimLevel: 0.35,
      hideSeconds: true,
      outlineHands: true,
      hideComplicationGauges: true,
    },
  },
  {
    id: 'preset-tactical-field',
    name: 'Field Tactical Ops 24',
    category: 'Sport',
    description: 'Rugged military compass dial with high-contrast night vision lume, battery telemetry, and altimeter bars.',
    shape: 'rugged',
    caseFinish: 'stealth_black',
    strap: 'silicone_black',
    bezel: {
      style: 'compass',
      bezelColor: '#171c18',
      textColor: '#86efac',
      accentColor: '#f59e0b',
      showGlassGlare: true,
      glareIntensity: 0.15,
    },
    dial: {
      backgroundType: 'minimal_grid',
      primaryColor: '#0f1410',
      secondaryColor: '#141c15',
      accentColor: '#22c55e',
      vignette: 0.5,
      innerRingRadius: 84,
      innerRingColor: '#233825',
      showInnerRing: true,
    },
    index: {
      style: 'military_24h',
      color: '#4ade80',
      glowColor: '#22c55e',
      showSubMinutes: true,
      subMinuteColor: '#2e5633',
      numberScale: 1.05,
      showCardinalsOnly: false,
    },
    timeDisplay: {
      type: 'hybrid',
      analog: {
        handStyle: 'tactical_arrow',
        hourHandColor: '#86efac',
        minuteHandColor: '#4ade80',
        secondHandColor: '#f59e0b',
        lumeColor: '#22c55e',
        sweepSeconds: false,
        showSeconds: true,
        centerCapColor: '#166534',
        centerCapSize: 9,
      },
      digital: {
        fontFamily: 'share_tech',
        format: '24h',
        showSeconds: true,
        showAmPm: false,
        blinkColon: true,
        textColor: '#86efac',
        glowColor: '#4ade80',
        x: 0,
        y: -14,
        fontSize: 22,
        letterSpacing: 2,
      },
    },
    brandText: {
      show: true,
      text: 'SPECIAL OPS',
      subtext: '200M RESISTANT',
      color: '#4ade80',
      y: -26,
    },
    complications: [
      {
        id: 'comp-tac-1',
        type: 'battery',
        style: 'linear_bar',
        x: -24,
        y: 12,
        scale: 1.0,
        color: '#4ade80',
        accentColor: '#22c55e',
        showIcon: true,
        showLabel: true,
        label: 'PWR',
      },
      {
        id: 'comp-tac-2',
        type: 'heart_rate',
        style: 'linear_bar',
        x: 24,
        y: 12,
        scale: 1.0,
        color: '#f87171',
        accentColor: '#ef4444',
        showIcon: true,
        showLabel: true,
        label: 'HR',
      },
      {
        id: 'comp-tac-3',
        type: 'weather',
        style: 'compact_badge',
        x: 0,
        y: 24,
        scale: 0.95,
        color: '#86efac',
        accentColor: '#4ade80',
        showIcon: true,
        showLabel: true,
        label: 'ENV',
      },
    ],
    aod: {
      enabled: true,
      dimLevel: 0.25,
      hideSeconds: true,
      outlineHands: true,
      hideComplicationGauges: true,
    },
  },
  {
    id: 'preset-submariner-ocean',
    name: 'Submariner Deep Sea',
    category: 'Luxury',
    description: 'Iconic dive watch with deep ocean blue dial, ceramic 60-min bezel, luminous dots, and Mercedes hands.',
    shape: 'round',
    caseFinish: 'stainless',
    strap: 'silicone_black',
    bezel: {
      style: 'diver60',
      bezelColor: '#0c1e38',
      textColor: '#ffffff',
      accentColor: '#38bdf8',
      showGlassGlare: true,
      glareIntensity: 0.35,
    },
    dial: {
      backgroundType: 'radial_gradient',
      primaryColor: '#08172e',
      secondaryColor: '#0f2b57',
      accentColor: '#38bdf8',
      vignette: 0.5,
      innerRingRadius: 84,
      innerRingColor: '#1e3a6a',
      showInnerRing: true,
    },
    index: {
      style: 'diver_dots',
      color: '#f0fdf4',
      glowColor: '#4ade80',
      showSubMinutes: true,
      subMinuteColor: '#334155',
      numberScale: 1.0,
      showCardinalsOnly: false,
    },
    timeDisplay: {
      type: 'analog',
      analog: {
        handStyle: 'mercedes',
        hourHandColor: '#f8fafc',
        minuteHandColor: '#f1f5f9',
        secondHandColor: '#38bdf8',
        lumeColor: '#4ade80',
        sweepSeconds: true,
        showSeconds: true,
        centerCapColor: '#38bdf8',
        centerCapSize: 8,
      },
      digital: {
        fontFamily: 'jetbrains',
        format: '24h',
        showSeconds: false,
        showAmPm: false,
        blinkColon: true,
        textColor: '#38bdf8',
        glowColor: '#4ade80',
        x: 0,
        y: 20,
        fontSize: 16,
        letterSpacing: 2,
      },
    },
    brandText: {
      show: true,
      text: 'SUBMARINER',
      subtext: '1000ft = 300m',
      color: '#e2e8f0',
      y: -22,
    },
    complications: [
      {
        id: 'comp-sub-1',
        type: 'date_window',
        style: 'compact_badge',
        x: 28,
        y: 0,
        scale: 1.05,
        color: '#0f172a',
        accentColor: '#38bdf8',
        showIcon: false,
        showLabel: false,
      },
      {
        id: 'comp-sub-2',
        type: 'battery',
        style: 'subdial_analog',
        x: 0,
        y: 22,
        scale: 0.95,
        color: '#f8fafc',
        accentColor: '#38bdf8',
        showIcon: true,
        showLabel: true,
        label: 'DEPTH',
      },
    ],
    aod: {
      enabled: true,
      dimLevel: 0.35,
      hideSeconds: true,
      outlineHands: true,
      hideComplicationGauges: true,
    },
  },
  {
    id: 'preset-monaco-racing',
    name: 'Monaco Heritage Racing',
    category: 'Sport',
    description: 'Legendary motorsport heritage square dial in Gulf racing livery blue & amber-orange.',
    shape: 'square',
    caseFinish: 'stainless',
    strap: 'leather_black',
    bezel: {
      style: 'clean',
      bezelColor: '#172554',
      textColor: '#f97316',
      accentColor: '#ea580c',
      showGlassGlare: true,
      glareIntensity: 0.25,
    },
    dial: {
      backgroundType: 'linear_gradient',
      primaryColor: '#1e3a8a',
      secondaryColor: '#172554',
      accentColor: '#f97316',
      vignette: 0.3,
      innerRingRadius: 85,
      innerRingColor: '#ea580c',
      showInnerRing: true,
    },
    index: {
      style: 'classic_baton',
      color: '#ffffff',
      glowColor: '#fed7aa',
      showSubMinutes: true,
      subMinuteColor: '#93c5fd',
      numberScale: 1.0,
      showCardinalsOnly: false,
    },
    timeDisplay: {
      type: 'analog',
      analog: {
        handStyle: 'baton',
        hourHandColor: '#ffffff',
        minuteHandColor: '#ffffff',
        secondHandColor: '#f97316',
        lumeColor: '#f97316',
        sweepSeconds: true,
        showSeconds: true,
        centerCapColor: '#f97316',
        centerCapSize: 8,
      },
      digital: {
        fontFamily: 'jetbrains',
        format: '24h',
        showSeconds: false,
        showAmPm: false,
        blinkColon: true,
        textColor: '#f97316',
        glowColor: '#fed7aa',
        x: 0,
        y: 20,
        fontSize: 16,
        letterSpacing: 2,
      },
    },
    brandText: {
      show: true,
      text: 'MONACO CALIBRE',
      subtext: 'AUTOMATIC CHRONO',
      color: '#ffffff',
      y: -22,
    },
    complications: [
      {
        id: 'comp-mon-1',
        type: 'battery',
        style: 'ring_gauge',
        x: -22,
        y: 0,
        scale: 0.95,
        color: '#ffffff',
        accentColor: '#f97316',
        showIcon: true,
        showLabel: true,
        label: 'RPM',
      },
      {
        id: 'comp-mon-2',
        type: 'heart_rate',
        style: 'ring_gauge',
        x: 22,
        y: 0,
        scale: 0.95,
        color: '#ffffff',
        accentColor: '#38bdf8',
        showIcon: true,
        showLabel: true,
        label: 'BPM',
      },
      {
        id: 'comp-mon-3',
        type: 'date_window',
        style: 'compact_badge',
        x: 0,
        y: 22,
        scale: 1.0,
        color: '#ffffff',
        accentColor: '#f97316',
        showIcon: false,
        showLabel: false,
      },
    ],
    aod: {
      enabled: true,
      dimLevel: 0.3,
      hideSeconds: true,
      outlineHands: true,
      hideComplicationGauges: true,
    },
  },
  {
    id: 'preset-tokyo-digital-84',
    name: 'Tokyo Neon 1984',
    category: 'Vintage',
    description: 'Retro 80s golden LCD wristwatch with high-contrast segmented digits and day-of-week bar.',
    shape: 'square',
    caseFinish: 'rosegold',
    strap: 'milanese_silver',
    bezel: {
      style: 'clean',
      bezelColor: '#272014',
      textColor: '#fbbf24',
      accentColor: '#f59e0b',
      showGlassGlare: true,
      glareIntensity: 0.2,
    },
    dial: {
      backgroundType: 'solid',
      primaryColor: '#18150f',
      secondaryColor: '#241f17',
      accentColor: '#f59e0b',
      vignette: 0.2,
      innerRingRadius: 88,
      innerRingColor: '#382f20',
      showInnerRing: true,
    },
    index: {
      style: 'none',
      color: '#fbbf24',
      glowColor: '#f59e0b',
      showSubMinutes: false,
      subMinuteColor: '#453c29',
      numberScale: 1.0,
      showCardinalsOnly: false,
    },
    timeDisplay: {
      type: 'digital',
      analog: {
        handStyle: 'baton',
        hourHandColor: '#fbbf24',
        minuteHandColor: '#fbbf24',
        secondHandColor: '#f59e0b',
        lumeColor: '#fbbf24',
        sweepSeconds: false,
        showSeconds: true,
        centerCapColor: '#f59e0b',
        centerCapSize: 7,
      },
      digital: {
        fontFamily: 'share_tech',
        format: '12h',
        showSeconds: true,
        showAmPm: true,
        blinkColon: true,
        textColor: '#fbbf24',
        glowColor: '#f59e0b',
        x: 0,
        y: -4,
        fontSize: 36,
        letterSpacing: 3,
      },
    },
    brandText: {
      show: true,
      text: 'CASIO·84',
      subtext: 'WATER 50M RESIST',
      color: '#d4af37',
      y: -28,
    },
    complications: [
      {
        id: 'comp-tokyo-1',
        type: 'day_date',
        style: 'compact_badge',
        x: 0,
        y: 20,
        scale: 1.05,
        color: '#fbbf24',
        accentColor: '#f59e0b',
        showIcon: false,
        showLabel: false,
      },
      {
        id: 'comp-tokyo-2',
        type: 'battery',
        style: 'compact_badge',
        x: -24,
        y: 20,
        scale: 0.9,
        color: '#fbbf24',
        accentColor: '#f59e0b',
        showIcon: true,
        showLabel: true,
        label: 'BAT',
      },
      {
        id: 'comp-tokyo-3',
        type: 'steps',
        style: 'compact_badge',
        x: 24,
        y: 20,
        scale: 0.9,
        color: '#fbbf24',
        accentColor: '#f59e0b',
        showIcon: true,
        showLabel: true,
        label: 'WALK',
      },
    ],
    aod: {
      enabled: true,
      dimLevel: 0.2,
      hideSeconds: true,
      outlineHands: false,
      hideComplicationGauges: true,
    },
  },
  {
    id: 'preset-nordic-polar',
    name: 'Nordic Polar Glacier',
    category: 'Minimal',
    description: 'Clean Scandinavian ice-blue sunburst dial with minimal faceted batons and vivid red second needle.',
    shape: 'round',
    caseFinish: 'ceramic',
    strap: 'milanese_silver',
    bezel: {
      style: 'clean',
      bezelColor: '#e2e8f0',
      textColor: '#0284c7',
      accentColor: '#ef4444',
      showGlassGlare: true,
      glareIntensity: 0.3,
    },
    dial: {
      backgroundType: 'sunburst',
      primaryColor: '#0c4a6e',
      secondaryColor: '#0284c7',
      accentColor: '#ef4444',
      vignette: 0.35,
      innerRingRadius: 82,
      innerRingColor: '#38bdf8',
      showInnerRing: true,
    },
    index: {
      style: 'classic_baton',
      color: '#f0f9ff',
      glowColor: '#38bdf8',
      showSubMinutes: true,
      subMinuteColor: '#7dd3fc',
      numberScale: 1.0,
      showCardinalsOnly: false,
    },
    timeDisplay: {
      type: 'analog',
      analog: {
        handStyle: 'minimal_needle',
        hourHandColor: '#f8fafc',
        minuteHandColor: '#f8fafc',
        secondHandColor: '#ef4444',
        lumeColor: '#38bdf8',
        sweepSeconds: true,
        showSeconds: true,
        centerCapColor: '#ef4444',
        centerCapSize: 7,
      },
      digital: {
        fontFamily: 'syne',
        format: '24h',
        showSeconds: false,
        showAmPm: false,
        blinkColon: true,
        textColor: '#f8fafc',
        glowColor: '#38bdf8',
        x: 0,
        y: 20,
        fontSize: 16,
        letterSpacing: 2,
      },
    },
    brandText: {
      show: true,
      text: 'NORDIC POLAR',
      subtext: 'STOCKHOLM',
      color: '#e0f2fe',
      y: -22,
    },
    complications: [
      {
        id: 'comp-nor-1',
        type: 'date_window',
        style: 'compact_badge',
        x: 0,
        y: 18,
        scale: 1.0,
        color: '#0f172a',
        accentColor: '#0284c7',
        showIcon: false,
        showLabel: false,
      },
      {
        id: 'comp-nor-2',
        type: 'weather',
        style: 'compact_badge',
        x: 0,
        y: -10,
        scale: 0.95,
        color: '#f0f9ff',
        accentColor: '#38bdf8',
        showIcon: true,
        showLabel: false,
      },
    ],
    aod: {
      enabled: true,
      dimLevel: 0.35,
      hideSeconds: true,
      outlineHands: true,
      hideComplicationGauges: true,
    },
  },
  {
    id: 'preset-aviator-gmt',
    name: 'Aviator Flieger GMT',
    category: 'Sport',
    description: 'High-altitude pilot instrument watch with 12/3/6/9 numerals, orange second zone, and compass bezel.',
    shape: 'rugged',
    caseFinish: 'titanium',
    strap: 'nato_olive',
    bezel: {
      style: 'numbered_12',
      bezelColor: '#181e24',
      textColor: '#f1f5f9',
      accentColor: '#f97316',
      showGlassGlare: true,
      glareIntensity: 0.25,
    },
    dial: {
      backgroundType: 'solid',
      primaryColor: '#111827',
      secondaryColor: '#1f2937',
      accentColor: '#f97316',
      vignette: 0.4,
      innerRingRadius: 80,
      innerRingColor: '#374151',
      showInnerRing: true,
    },
    index: {
      style: 'arabic_sport',
      color: '#f9fafb',
      glowColor: '#fde047',
      showSubMinutes: true,
      subMinuteColor: '#6b7280',
      numberScale: 1.15,
      showCardinalsOnly: true,
    },
    timeDisplay: {
      type: 'analog',
      analog: {
        handStyle: 'pilot_flieger',
        hourHandColor: '#f9fafb',
        minuteHandColor: '#f9fafb',
        secondHandColor: '#f97316',
        lumeColor: '#fde047',
        sweepSeconds: true,
        showSeconds: true,
        centerCapColor: '#f97316',
        centerCapSize: 9,
      },
      digital: {
        fontFamily: 'share_tech',
        format: '24h',
        showSeconds: false,
        showAmPm: false,
        blinkColon: true,
        textColor: '#f9fafb',
        glowColor: '#f97316',
        x: 0,
        y: 20,
        fontSize: 16,
        letterSpacing: 2,
      },
    },
    brandText: {
      show: true,
      text: 'FLIEGER·GMT',
      subtext: 'DUAL TIME UTC',
      color: '#9ca3af',
      y: -22,
    },
    complications: [
      {
        id: 'comp-flieger-1',
        type: 'battery',
        style: 'ring_gauge',
        x: -24,
        y: 0,
        scale: 0.95,
        color: '#f9fafb',
        accentColor: '#f97316',
        showIcon: true,
        showLabel: true,
        label: 'ALT',
      },
      {
        id: 'comp-flieger-2',
        type: 'date_window',
        style: 'compact_badge',
        x: 24,
        y: 0,
        scale: 1.0,
        color: '#f9fafb',
        accentColor: '#f97316',
        showIcon: false,
        showLabel: false,
      },
    ],
    aod: {
      enabled: true,
      dimLevel: 0.3,
      hideSeconds: true,
      outlineHands: true,
      hideComplicationGauges: true,
    },
  },
  {
    id: 'preset-tourbillon-skeleton',
    name: 'Tourbillon Obsidian',
    category: 'Luxury',
    description: 'High-horology skeleton tourbillon with brushed guilloché dial, golden dauphine hands, and power reserve.',
    shape: 'round',
    caseFinish: 'obsidian',
    strap: 'leather_black',
    bezel: {
      style: 'clean',
      bezelColor: '#121216',
      textColor: '#d4af37',
      accentColor: '#d4af37',
      showGlassGlare: true,
      glareIntensity: 0.35,
    },
    dial: {
      backgroundType: 'guilloche',
      primaryColor: '#0a0a0d',
      secondaryColor: '#141419',
      accentColor: '#d4af37',
      vignette: 0.5,
      innerRingRadius: 78,
      innerRingColor: '#2b2923',
      showInnerRing: true,
    },
    index: {
      style: 'roman_luxury',
      color: '#d4af37',
      glowColor: '#fde68a',
      showSubMinutes: true,
      subMinuteColor: '#5c543f',
      numberScale: 1.0,
      showCardinalsOnly: false,
    },
    timeDisplay: {
      type: 'analog',
      analog: {
        handStyle: 'skeleton',
        hourHandColor: '#d4af37',
        minuteHandColor: '#fde68a',
        secondHandColor: '#d4af37',
        lumeColor: '#fde68a',
        sweepSeconds: true,
        showSeconds: true,
        centerCapColor: '#d4af37',
        centerCapSize: 10,
      },
      digital: {
        fontFamily: 'cinzel',
        format: '24h',
        showSeconds: false,
        showAmPm: false,
        blinkColon: false,
        textColor: '#d4af37',
        glowColor: '#fde68a',
        x: 0,
        y: 20,
        fontSize: 16,
        letterSpacing: 2,
      },
    },
    brandText: {
      show: true,
      text: 'TOURBILLON',
      subtext: 'FLYING ESCAPEMENT',
      color: '#d4af37',
      y: -24,
    },
    complications: [
      {
        id: 'comp-tour-1',
        type: 'battery',
        style: 'subdial_analog',
        x: 0,
        y: 20,
        scale: 1.1,
        color: '#d4af37',
        accentColor: '#d4af37',
        showIcon: false,
        showLabel: true,
        label: 'RESERVE',
      },
      {
        id: 'comp-tour-2',
        type: 'moon_phase',
        style: 'subdial_analog',
        x: 0,
        y: -12,
        scale: 1.0,
        color: '#d4af37',
        accentColor: '#60a5fa',
        showIcon: false,
        showLabel: false,
      },
    ],
    aod: {
      enabled: true,
      dimLevel: 0.35,
      hideSeconds: true,
      outlineHands: true,
      hideComplicationGauges: true,
    },
  },
];
